version: '3'

networks:
  inception:
    name: inception
    driver: bridge

# volumes:
#   wp:
#     driver: local
#     name: wp
#     driver_opts:
#       type: none
#       o: bind
#       device: /root/data/wp
#   db:
#     driver: local
#     name: db
#     driver_opts:
#       type: none
#       o: bind
#       device: /root/data/db

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb


services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    depends_on: 
      - wordpress
    volumes: 
      - wp:/var/www/html
    networks: 
      - inception
    restart: on-failure
    ports: 
      - "443:443"

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes: 
      - db:/var/lib/mysql
    networks: 
      - inception
    restart: unless-stopped
    expose: 
      - "3306"

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    depends_on: 
      - mariadb
    volumes: 
      - wp:/var/www/html
    networks: 
      - inception
    restart: on-failure
    expose: 
      - "9000"